services:
   php-fpm:
      restart: unless-stopped
      env_file:
         - ./app/.env
      image: ${DOCKER_REGISTRY}/stm/php:${TAG:-latest}
      container_name: stm_php
      networks:
         - internal

   supervisor:
      restart: unless-stopped
      env_file:
         - ./app/.env
      image: ${DOCKER_REGISTRY}/stm/supervisor:${TAG:-latest}
      container_name: stm_supervisor
      depends_on:
         - db
      networks:
         - internal

   nginx:
      restart: unless-stopped
      env_file:
         - ./app/.env
      container_name: stm_nginx
      image: ${DOCKER_REGISTRY}/stm/nginx:${TAG:-latest}
      ports:
         - "1242:80"
      depends_on:
         - php-fpm
      networks:
         - internal

   db:
      image: postgres:17.6
      env_file:
         - ./app/.env
      restart: unless-stopped
      container_name: stm_db
      environment:
         POSTGRES_USER: user1
         POSTGRES_PASSWORD: password1
         POSTGRES_DB: stmdb
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
         timeout: 5s
         retries: 5
         start_period: 60s
      ports:
         - "6432:5432"
      volumes:
         - ./.db:/var/lib/postgresql/data
      networks:
         - internal

networks:
   internal:
      driver: bridge
      ipam:
         driver: default
