[supervisord]
nodaemon=true
logfile = /dev/null
pidfile = /tmp/supervisord.pid
childlogdir = /var/log/supervisor

[program:tg-bot]
command=php /home/app/bin/console app:telegram-bot:run
directory=/home/app
user=www-data
autostart=true
autorestart=true
startretries=10
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0